services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - ddd-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_MULTIPLE_DATABASES: "app_db,app_test_db"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - ddd-network
    restart: unless-stopped

networks:
  ddd-network:
    name: ddd-network
    driver: bridge
